-- ============================================================
-- Galu-CRM — Cierre de la base de datos (RLS)
-- ============================================================
-- CONTEXTO: la app usa NEXT_PUBLIC_SUPABASE_ANON_KEY, que viaja en el bundle
-- del navegador y por lo tanto es pública. Con RLS desactivada, cualquiera
-- que la lea puede consultar y borrar TODAS las tablas sin pasar por la app.
-- El login del panel no alcanza: hay que cerrar también la base.
--
-- Este script deja las tablas accesibles SOLO para el rol `service_role`
-- (la clave secreta del servidor) y sin acceso para `anon`.
--
-- 🛑 NO EJECUTAR TODAVÍA — NINGÚN BLOQUE.
--
-- Una versión anterior de este archivo decía que el bloque 1 se podía aplicar
-- de inmediato "porque ninguna pantalla pública usa esas tablas". Estaba mal:
-- Finanzas, Cotizaciones e Infraestructura son pantallas privadas, pero leen
-- Supabase DESDE EL NAVEGADOR con la anon key. Al revocarla, dejan de andar.
--
-- REGLA: activar RLS en una tabla exige, PRIMERO, que sus lecturas pasen por
-- el servidor (ver "Requisito previo" abajo). No hay atajo tabla por tabla.
--
-- Si ya ejecutaste el bloque 1, corré: 20260806_rollback_bloque1.sql
--
-- ─────────────────────────────────────────────────────────────
-- REQUISITO PREVIO — la "migración al servidor"
-- ─────────────────────────────────────────────────────────────
-- Hoy `src/lib/store.ts` corre en el navegador y habla directo con Supabase
-- usando NEXT_PUBLIC_SUPABASE_ANON_KEY. Esa clave está dentro del JavaScript
-- que se descarga el visitante: es pública por diseño. Con RLS apagada, esa
-- clave puede leer y borrar todo.
--
-- Activar RLS bloquea a `anon`... y por lo tanto bloquea a la propia app,
-- porque la app ES `anon`.
--
-- La migración consiste en:
--   1. Crear SUPABASE_SERVICE_ROLE_KEY como variable de entorno (SIN el
--      prefijo NEXT_PUBLIC_, para que nunca llegue al navegador).
--   2. Mover las consultas de store.ts a rutas de API en el servidor, que ya
--      están protegidas por el login del middleware.
--   3. Que el navegador llame a esas rutas en vez de a Supabase.
--   4. Recién ahí, activar RLS con este archivo.
--
-- El portal del cliente y los briefs también tienen que leer desde el
-- servidor filtrando por slug, porque los abre gente sin login.
-- ============================================================

-- ─────────────────────────────────────────────────────────────
-- BLOQUE 1 — Tablas más sensibles.
-- ─────────────────────────────────────────────────────────────

-- ALTER TABLE finanzas        ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE cotizaciones    ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE infraestructura ENABLE ROW LEVEL SECURITY;
-- REVOKE ALL ON finanzas, cotizaciones, infraestructura FROM anon;

-- ─────────────────────────────────────────────────────────────
-- BLOQUE 2 — El resto del CRM.
-- ─────────────────────────────────────────────────────────────

-- ALTER TABLE clientes          ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE proyectos         ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE tareas            ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE briefs            ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE recursos          ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE tickets           ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE ideas             ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE logs_proyecto     ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE scraper_busquedas ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE prospectos        ENABLE ROW LEVEL SECURITY;
-- REVOKE ALL ON clientes, proyectos, tareas, briefs, recursos, tickets,
--               ideas, logs_proyecto, scraper_busquedas, prospectos FROM anon;

-- Recordatorio aparte: `proyectos.accesos` guarda usuarios y contraseñas de
-- clientes en texto plano. Aunque cierres la base, conviene sacarlos de ahí
-- y moverlos a un gestor de contraseñas.
